Feat/OINK-1210, Balance History endpoint
Alcancia-io/Alcancia-BackEnd pull request #101
Opened 2023-08-10 21:41 UTC by pellerano

- feat: updated getUserBalanceHistory

2023-08-15 14:54 UTC, edwardtineob commented
Good

2023-08-15 14:56 UTC, edwardtineob approved these changes
Lgtm

2023-08-15 15:01 UTC, xeno097 requested changes

2023-08-15 15:01 UTC, xeno097 commented on src/metamap/metamap.service.ts
> +    let curp = !(subtype === 'credencial-para-votar' || subtype === 'Credencial Para Votar') ? null : fields.curp.value;
It would be nice if all the possible values of subtype were stored in constants to avoid having hardcoded strings.

2023-08-16 05:38 UTC, bujosa commented on src/metamap/metamap.service.ts
> +    let curp = !(subtype === 'credencial-para-votar' || subtype === 'Credencial Para Votar') ? null : fields.curp.value;
Yeah like enum or something like that

2023-08-17 21:25 UTC, xeno097 approved these changes

2023-08-17 21:39 UTC, bujosa approved these changes

2023-08-17 21:40 UTC, merged