Feat/OINK-1215, Migrate wallet keys from S3 to KMS
Alcancia-io/Alcancia-BackEnd pull request #102
Opened 2023-08-24 01:20 UTC by pellerano

2023-08-24 01:24 UTC, pellerano commented
Pueden ir aprobando si les parece bien, pero aun no le hagan merge. Aun quiero probar con transacciones para confirmar de que esta funcionando todo.

2023-08-24 01:31 UTC, xeno097 requested changes

2023-08-24 01:31 UTC, xeno097 commented on src/wallets/wallets.resolver.ts
> +  // }
Should this be commented out?

2023-08-24 01:31 UTC, xeno097 commented on src/utils/constants/index.ts
> +};
Maybe this should be an environment variable

2023-08-24 01:31 UTC, xeno097 commented on src/wallets/wallets.service.ts
> +    const { priv } = await this.getKeysFromKMS(userId);
Maybe it would be a good idea to keep a call to the `getKeysFromAws` method in case the `getKeysFromKMS` does not find the private key and then remove it after we are sure that the migration was successful and there was no data loss.

2023-08-24 01:31 UTC, xeno097 commented on src/wallets/wallets.service.ts
> +    const src = deposit ? this.alcanciaDOPTxnPrivateKey : (await this.getKeysFromKMS(srcUserId)).priv;
Same here

2023-08-24 01:31 UTC, xeno097 commented on src/wallets/wallets.service.ts
> +
We should consider moving this logic to its own service when we start the refactor

2023-08-24 21:57 UTC, pellerano commented on src/wallets/wallets.service.ts
> +    const { priv } = await this.getKeysFromKMS(userId);
I'll revert it back to the original function and rename it to S3 instead of AWS since that's more specific.

2023-08-24 21:57 UTC, pellerano commented on src/wallets/wallets.service.ts
> +    const src = deposit ? this.alcanciaDOPTxnPrivateKey : (await this.getKeysFromKMS(srcUserId)).priv;
Same here.

2023-08-24 21:58 UTC, pellerano commented on src/wallets/wallets.service.ts
> +
I'll probably just move it to its own service file now.

2023-08-24 23:25 UTC, xeno097 requested changes

2023-08-24 23:25 UTC, xeno097 commented on src/alcancia/alcancia.service.ts
> +    @Inject(forwardRef(() => AwsService)) private awsService: AwsService,
You can simply inject the `AwsService` with `private awsService: AwsService` because the `AlcanciaService` does not have a cyclic dependency with the `AwsService`

2023-08-24 23:25 UTC, xeno097 commented on src/wallets/wallets.module.ts
> +    forwardRef(() => AwsModule),
I think that you can remove the `forwardRef` call and simply put the `AswModule` in the imports array as there isn't a cyclic dependency between the `WalletModule` and the `AwsModule`

2023-08-24 23:25 UTC, xeno097 commented on src/aws/aws.resolver.ts
> +    if (process.env.NODE_ENV === 'DEV') return this.awsService.migrateFromS3ToKMS();
You should have a default return statement as the query will throw an error because if the `NODE_ENV` var is not `DEV` then nothing will be returned by the method and the graphql server will complain. I suppose this is something that will be used to migrate the data from a S3 bucket to KMS and will only be run locally by someone after a production deployment but should we leave this query open to anyone to run it?

2023-08-24 23:25 UTC, xeno097 commented on src/alcancia/alcancia.module.ts
> +    forwardRef(() => AwsModule),
I think that you can remove the `forwardRef` call and simply put the `AswModule` in the imports array as there isn't a cyclic dependency between the `AlcanciaModule` and the `AwsModule`

2023-08-24 23:25 UTC, xeno097 commented on src/aws/aws.service.ts
> +    const kmsKeyDetails = new DescribeKeyCommand({ KeyId: kmsKeyId });
Having a look at the docs for [ListAliasesCommand](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-kms/classes/listaliasescommand.html) It seems that you can pass as filter the `KeyId` property so you can get the user's alias without having to filter the whole list after fetching all the records.

2023-08-24 23:25 UTC, xeno097 commented on src/aws/aws.service.ts
> +  async getKeysFromKMS(userId?: string) {
can you add a type to describe the kind of output that this function will return? Something like:

```typescript
interface UserKeyPair {
    privateKey: string;
    publicKey: string;
}
```

2023-08-24 23:25 UTC, xeno097 commented on src/aws/aws.service.ts
> +  async uploadKeysToKMS(privateKey: string | SigningKey, publicKey: string | SigningKey, userId: string) {
Can you add typing here too?

2023-08-24 23:25 UTC, xeno097 commented on src/aws/aws.service.ts
> +    });
Is there a reason why you are awaiting and chaining a `then` to the promise? I think you can simplify the statement by rewriting it like this:

```typescript
    const data = await kmsClient.send(kmsKeyDetails);

    const keys = data.KeyMetadata.Description.split('/');
    return { pub: keys[0], priv: keys[1] };
```

2023-08-24 23:25 UTC, xeno097 commented on src/aws/aws.service.ts
> +    });
Same `then` comment as below

2023-08-24 23:34 UTC, pellerano commented on src/aws/aws.service.ts
> +    const kmsKeyDetails = new DescribeKeyCommand({ KeyId: kmsKeyId });
The issue with that is that you need to know the `KeyId` value you want to look up, which we don't.

2023-08-24 23:40 UTC, pellerano commented on src/aws/aws.service.ts
> +  async uploadKeysToKMS(privateKey: string | SigningKey, publicKey: string | SigningKey, userId: string) {
By typing, do you mean addiing a return type?

2023-08-24 23:51 UTC, xeno097 commented on src/aws/aws.service.ts
> +  async uploadKeysToKMS(privateKey: string | SigningKey, publicKey: string | SigningKey, userId: string) {
yup

2023-08-24 23:56 UTC, xeno097 commented on src/aws/aws.service.ts
> +    const kmsKeyDetails = new DescribeKeyCommand({ KeyId: kmsKeyId });
Can't we store the associated `targetKeyId` for a user on wallet creation? so we can avoid querying unnecessary data

2023-08-25 00:03 UTC, pellerano commented on src/aws/aws.service.ts
> +    const kmsKeyDetails = new DescribeKeyCommand({ KeyId: kmsKeyId });
`targetKeyId` is auto-generated. If you want to store the associated `targetKeyId` on wallet creation we can either add another column to the user table in our DB or have an entirely separate table.

2023-08-25 00:14 UTC, xeno097 commented on src/aws/aws.service.ts
> +    const kmsKeyDetails = new DescribeKeyCommand({ KeyId: kmsKeyId });
Yeah, I'd prefer that because when the user base grows the amount of data fetched from was will also grow making the whole operation slower. I think that we can store it in the user table and then we start refactoring the backend we can create a new table that holds the wallet information for a user.

2023-08-25 00:59 UTC, pellerano commented on src/aws/aws.service.ts
> +    const kmsKeyDetails = new DescribeKeyCommand({ KeyId: kmsKeyId });
Done.

2023-08-25 01:25 UTC, xeno097 commented on src/aws/aws.service.ts
> +    const kmsKeyDetails = new DescribeKeyCommand({ KeyId: kmsKeyId });
Nice will you be writing a migration to add that data to the new field or a script?

2023-08-25 01:40 UTC, pellerano commented on src/aws/aws.service.ts
> +    const kmsKeyDetails = new DescribeKeyCommand({ KeyId: kmsKeyId });
Script most likely.

2023-08-25 05:39 UTC, pellerano commented on src/aws/aws.service.ts
> +    const kmsKeyDetails = new DescribeKeyCommand({ KeyId: kmsKeyId });
Done. Added `walletKeyId` to the user entity.

2023-08-29 01:33 UTC, xeno097 approved these changes

2023-08-30 21:44 UTC, merged