Redeem Referral Endpoint
Alcancia-io/Alcancia-BackEnd pull request #106
Opened 2023-09-07 01:00 UTC by pellerano

- Adds the new redeemReferral endpoint for the ReferralModule
- Adds 2 new environment variables:
  - `REFERRAL_PAYOUT_AMOUNT`
  - `REFERRAL_PAYOUT_TOKEN`

- Adds the following new graphql operations:
    - redeemReward

NOTE 1: This PR adds 1 new environment variable that should be set in production before deploying the backend otherwise it will not start.

2023-09-07 02:03 UTC, xeno097 requested changes

2023-09-07 02:03 UTC, xeno097 commented on src/alcancia/alcancia.service.ts
> +  }
Why don't you move this logic inside the `RedeemRewardUseCase` instead so that you don't have to introduce a circular dependency between the `AlcanciaModule` and the `ReferralModule`?

2023-09-07 20:18 UTC, xeno097 requested changes

2023-09-07 20:18 UTC, xeno097 commented on src/referral/use-cases/redeem-reward.use-case.ts
> +    }
I think you can move the `payoutReward` method implementation in the `execute` method body  because the only thing that the `execute` method is doing is calling `payoutReward` which is kinda pointless

2023-09-08 19:46 UTC, xeno097 approved these changes

2023-09-11 22:30 UTC, bujosa approved these changes

2023-09-13 00:13 UTC, merged