OINK-1329 - Transaction Module Refactor
Alcancia-io/Alcancia-BackEnd pull request #132
Opened 2023-12-12 23:53 UTC by pellerano

2023-12-13 01:42 UTC, xeno097 requested changes
You are on the right track but remember to use the base errors like `BaseInternalError` and `BaseError` to create errors instead of the Apollo error class as that is something specific to a graphql API and should not be used in the core layer.

2023-12-13 01:42 UTC, xeno097 commented on src/modules/transaction/api/graphql/transactions.resolver.new.ts
> +  }
There is a new decorator called `JwtPayload` that returns the user information, please use that instead of the `Context` decorator. Also is this a crypto withdrawal or a bank withdrawal? The 2 withdrawal flows should be separated and we should try to be as explicit as possible. Considering the context of the PR you are working on the bank withdrawals so this should be called something like `withdrawToBankAccount`.

2023-12-13 01:42 UTC, xeno097 commented on src/modules/transaction/core/use-cases/withdraw.use-case.ts
> +  }
This should throw an error if no valid currency is provided. Instead of having hardcoded strings, we should have a `SupportedCurrency` enum to describe all the possible values for a currency that we currently support.

```typescript
export enum SupportedCurrency {
    MXN = "MXN",
    DOP = "DOP
}
```

Don't forget to add types everywhere as looking at the code as it is, it is not clear what the return type of this use case is and we also lose type safety

2023-12-13 01:42 UTC, xeno097 commented on src/modules/transaction/core/use-cases/withdraw.use-case.ts
> +}
Consider creating a type that has unnested fields. It should have all the fields in the OrderInput type + the userId field. Remember that we should not use types from the API layer in the business logic layer.

2023-12-13 01:42 UTC, xeno097 commented on src/modules/transaction/core/use-cases/mx-withdraw.use-case.ts
> +    @InjectRepository(Transaction) private txnRepository: Repository<Transaction>
Please remember to implement an abstraction over typeorm own repository class instead of using it directly.

2023-12-13 01:42 UTC, xeno097 commented on src/modules/transaction/core/use-cases/dr-withdraw.use-case.ts
> +    @InjectRepository(Transaction) private txnRepository: Repository<Transaction>
Same comment as below, also try to avoid abbreviations when naming variables to make things as clear as possible. Example `txnRepository` should be `transactionRepository`

2023-12-13 01:42 UTC, xeno097 commented on src/modules/transaction/core/services/transaction.service.new.ts
> +}
This should be a repository as you are using database-specific objects, try to use objects instead of a long list of parameters. When using enums try to not access them using the index syntax. `TransactionStatus["PENDING"]` should be  `TransactionStatus.PENDING`.

2023-12-13 01:42 UTC, xeno097 commented on src/modules/transaction/core/services/alcancia.service.new.ts
> +    method['concepto'] = concepto;
Create a type for the method variable and avoid using indexed access.

2023-12-13 01:42 UTC, xeno097 commented on src/modules/transaction/core/services/alcancia.service.new.ts
> +      provider: 'ALCANCIA',
We should add an enum to describe all the kind of provider that we support instead of using hardcoded string

2023-12-13 01:42 UTC, xeno097 commented on src/modules/transaction/core/services/alcancia.service.new.ts
> +    if (type === 'WITHDRAW' && !bank_account)
We should create an enum for the supported types of transactions

2023-12-13 01:42 UTC, xeno097 commented on src/modules/transaction/core/services/alcancia.service.new.ts
> +    const formattedOrderInput = await this.formatOrderInput(orderInput);
Remember to add types to function signatures

2023-12-13 01:42 UTC, xeno097 commented on src/modules/transaction/core/services/suarmi.service.new.ts
> +  }
Please remember to only put logic that communicates with the suarmi API here. As suarmi is an external depency it should be moved to the infra layer and be "downgraded" to a provider instead of being a service

2023-12-13 05:11 UTC, pellerano commented on src/modules/transaction/core/services/alcancia.service.new.ts
> +      provider: 'ALCANCIA',
Used existing AllowedProviders enum and added ALCANCIA as an option.

2023-12-13 21:59 UTC, DHurtado714-itesm requested changes

2023-12-13 21:59 UTC, DHurtado714-itesm commented on src/modules/transaction/core/services/suarmi.service.new.ts
> +    try {
Maybe you should check if the user is mexican, before splitting the phone number.

2023-12-13 21:59 UTC, DHurtado714-itesm commented on src/modules/transaction/core/services/suarmi.service.new.ts
> +    } catch (e: any) {
Keep consistency in error variable, choose error or e, not both.

2023-12-13 21:59 UTC, DHurtado714-itesm commented on src/modules/transaction/core/services/suarmi.service.new.ts
> +    if (res.status != 201) throw new ApolloError('Error al crear orden de compra en Suarmi');
As suggestion, maybe we could also throw the error code for better debugging

2023-12-13 21:59 UTC, DHurtado714-itesm commented on src/modules/transaction/core/services/transactions.service.ts
> +      response.from_currency = SupportedCurrency.USDC;
I like this 😍

2023-12-13 21:59 UTC, DHurtado714-itesm commented on src/modules/transaction/core/use-cases/dr-withdraw.use-case.ts
> +
If you are going to comment the code, do it in a specific format. We should discuss it with @xeno097

2023-12-13 23:24 UTC, pellerano commented on src/modules/transaction/core/services/suarmi.service.new.ts
> +    try {
If its suarmi, then it's mexico.

2023-12-19 01:02 UTC, DHurtado714-itesm approved these changes

2023-12-19 01:36 UTC, xeno097 requested changes

2023-12-19 01:36 UTC, xeno097 commented on src/modules/transaction/core/domain/entities/transaction.entity.ts
> +  userID?: EntityId;
please rename this to `userId`

2023-12-19 01:36 UTC, xeno097 commented on src/modules/transaction/core/domain/entities/transaction.entity.ts
> +  transactionID?: EntityId;
Please rename this to `transactionId`

2023-12-19 01:36 UTC, xeno097 commented on src/modules/transaction/core/domain/entities/transaction.entity.ts
> +  paymentGatewayID?: EntityId;
Please rename this to `paymentGatewayId`

2023-12-19 01:36 UTC, xeno097 commented on src/modules/transaction/infra/libs/suarmi/suarmi.provider.ts
> +    const { walletAddress } = user;
you should pass these values to the `sendOrder` method instead of having to fetch them here

2023-12-19 01:36 UTC, xeno097 commented on src/modules/transaction/infra/libs/suarmi/suarmi.provider.ts
> +    if (type === TransactionType.WITHDRAW && !bank_account) throw new InvalidBankAccountError();
you should create a type that does not allow the bank account value to be undefined considering that this is required for performing a bank withdrawal. Just to clarify something, with suarmi can you create other types of orders or can you only withdraw to a bank?

2023-12-19 01:36 UTC, xeno097 commented on src/modules/transaction/core/use-cases/withdraw.use-case.ts
> +  }
You should throw an error if the end of the method is reached because this means that none of the previous cases has been matched

2023-12-19 01:36 UTC, xeno097 commented on src/modules/transaction/infra/libs/suarmi/suarmi.provider.ts
> +  }
this should be an external function instead of a class method. Also, define a return type for this function.

2023-12-19 01:36 UTC, xeno097 commented on src/modules/transaction/infra/libs/suarmi/suarmi.provider.ts
> +      await this.userRepository.save({ ...user, suarmi: uuid });
You shouldn't be using the `userRepository` here. Saving the user data after the user has been created in the 3rd party API should be done in the use case/ service method that requires the user to be created in the 3rd party service

2023-12-19 01:36 UTC, xeno097 commented on src/modules/transaction/infra/libs/suarmi/suarmi.provider.ts
> +      id: EntityId.fromString(uuid()),
you should be using the `EntityId.new` method if you want a new uuid.

2023-12-19 16:16 UTC, pellerano commented on src/modules/transaction/api/graphql/input-types/method.input.ts
>  }
I think this might cause some issues, since the value is being used in the DB.

2023-12-19 16:23 UTC, pellerano commented on src/modules/transaction/core/services/transactions.service.ts
>      return response;
changed back to 'usdc'

2023-12-19 16:53 UTC, pellerano commented on src/modules/transaction/infra/libs/suarmi/suarmi.provider.ts
> +    if (type === TransactionType.WITHDRAW && !bank_account) throw new InvalidBankAccountError();
both withdrawal and deposits for MX are managed through Suarmi.

2023-12-19 21:49 UTC, xeno097 commented on src/modules/transaction/api/graphql/input-types/method.input.ts
>  }
The point of splitting types per layer is exactly to avoid that you can have that field be called `concepto` in the database but that can have a completely different name in the other layers

2023-12-19 21:50 UTC, xeno097 commented on src/modules/transaction/infra/libs/suarmi/suarmi.provider.ts
> +    if (type === TransactionType.WITHDRAW && !bank_account) throw new InvalidBankAccountError();
yup you should do that please because it's clearer that way and we can ensure that each flow has the expected type

2023-12-21 02:06 UTC, xeno097 requested changes

2023-12-21 02:06 UTC, xeno097 commented on src/modules/transaction/core/infra/suarmi-provider.ts
> +}
Based on my comment in the suarmi provider file this should be split into 2 types one for withdrawals and one for deposits

2023-12-21 02:06 UTC, xeno097 commented on src/modules/transaction/core/infra/suarmi-provider.ts
> +  'id-number': string;
you should rename the fields like `ext-num`  and the others that are in `snake_case` to be in `camelCase` and if that is the format expected or received by the suarmi API then implement an intermediary type that has the required format and parse it. As an example have a look at the 0x integration and the distinction between raw types from the API and our internal types

2023-12-29 01:40 UTC, xeno097 requested changes

2023-12-29 01:40 UTC, xeno097 commented on src/modules/transaction/infra/libs/suarmi/entities/suarmi-user.entity.ts
> +}
This is not allowed as you are importing an interface from another module

2023-12-29 01:40 UTC, xeno097 commented on src/modules/transaction/infra/repositories/transaction.repository.ts
> +        }
Should all these fields be updated? I don't think that we should change the `type` of a transaction once it has been created nor the `createdAt` field

2024-01-01 15:35 UTC, xeno097 approved these changes

2024-01-09 23:12 UTC, xeno097 requested changes

2024-01-09 23:12 UTC, xeno097 commented on src/modules/transaction/core/use-cases/mx-withdraw.use-case.ts
> +  ) {}
Same comment about inject repository as the others

2024-01-09 23:12 UTC, xeno097 commented on src/modules/transaction/infra/libs/alcancia/alcancia.provider.ts
> +  }
Return types are missing in both methods

2024-01-09 23:12 UTC, xeno097 commented on src/modules/transaction/core/use-cases/get-balance-history.use-case.ts
> +  constructor(@InjectRepository(BalanceHistoryDBModel) private balanceHistoryRepository: IBalanceHistoryRepository) {}
Same comment about inject repository

2024-01-09 23:12 UTC, xeno097 commented on src/modules/transaction/core/use-cases/get-balance-history.use-case.ts
> +}
Please rename the `userId` field to `id` and the type to `GetBalanceHsitoryByUserIdDto`

2024-01-10 00:18 UTC, pellerano commented on .vscode/settings.json
>  }
It's already in the `.gitignore`

2024-01-10 03:32 UTC, pellerano commented on src/modules/transaction/infra/libs/alcancia/alcancia.provider.ts
> +  }
I took a closer look at the code, and this is not being used anywhere 🤔, I'll still add the return types to their appropriate use cases.

2024-01-11 22:14 UTC, merged