Refactor Metamap to Modular Monolith Architecture
Alcancia-io/Alcancia-BackEnd pull request #135
Opened 2023-12-19 01:01 UTC by DHurtado714-itesm

Description:

Refactor KYC provider logic into 3 layers(Repository, Service, Metamap provider).

2023-12-19 17:18 UTC, pellerano commented on src/modules/user/core/services/kyc.service.new.ts
This file feels redundant since @xeno097 already created a `kyc.repository.ts` that essentially works the same 🤔

2023-12-19 17:20 UTC, pellerano commented on src/utils/constants/index.ts
> +    REVIEW_NEEDED: 'pending',
Shouldn't this be `PENDING`?

2023-12-19 21:45 UTC, xeno097 requested changes

2023-12-19 21:45 UTC, xeno097 commented on src/modules/user/api/webhook/metamap.webhook.ts
> +  async completeVerification(@Req() request: Request) {
can you create a type definition for the expected payload received by metamap when calling this endpoint? Using the `Request` type from express/nestjs does not help us with type safety

2023-12-19 21:45 UTC, xeno097 commented on src/modules/user/core/errors/Metamap/internal-server.error.ts
> +}
This can be removed has the `core` folder already defines an internal server error
![image](https://github.com/Alcancia-io/Alcancia-BackEnd/assets/42520800/ac390cad-93aa-4e10-afd5-eaf45c14f6c3)

2023-12-19 21:45 UTC, xeno097 commented on src/modules/user/core/services/kyc.service.new.ts
> +    const currentKyc = await this.kycRepository.getByUserId(userIdEntity);
Consider that this will throw an error if the kyc data does not exist for the provided user id. Considering that this method is called createKycData this should verify if kyc exists with the provided user id and throw an error if it does because is not the expected behaviour when you try to create a resource.
![image](https://github.com/Alcancia-io/Alcancia-BackEnd/assets/42520800/3b1a4698-c52e-44c9-960b-711b9c4282a7)

2023-12-19 21:45 UTC, xeno097 commented on src/modules/user/infra/repositories/kyc.repository.ts
> +  }
this should be a function instead of a private method in the class

2023-12-19 21:45 UTC, xeno097 commented on src/modules/user/infra/repositories/kyc.repository.ts
> +      }
this can be omitted if something like this can happen we need to make the current typescript rules more strict and also add input validations when receiving the data from metamap

2023-12-19 21:45 UTC, xeno097 commented on src/utils/constants/index.ts
> +  };
This should probably be an enum

2023-12-19 21:45 UTC, xeno097 commented on src/modules/user/core/errors/Metamap/resource-not-found.error.ts
> +}
You can reuse the `NotFoundError` instead of creating a new error only for the kyc
![image](https://github.com/Alcancia-io/Alcancia-BackEnd/assets/42520800/9b2dfd0e-7b1f-466c-8690-862f58137228)

2023-12-19 21:45 UTC, xeno097 commented on src/modules/user/core/services/kyc.service.new.ts
> +
remember to remove this in this case is not needed a function to wrap this logic you can directly use the `getById` method from the user repository where needed

2023-12-19 21:45 UTC, xeno097 commented on src/modules/user/core/services/kyc.service.new.ts
> +    }
In which scenario is this possible? Can we avoid having these fields set to undefined?

2023-12-19 21:45 UTC, xeno097 commented on src/modules/user/core/services/kyc.service.new.ts
> +        await this.updateUserVerified(resourceData.metadata.ui, 'PENDING');
Following along with other conditions, shouldn't this be `resourceData.metadata.uid`? That is why correctly typing variables is important

2023-12-19 21:45 UTC, xeno097 commented on src/modules/user/core/services/kyc.service.new.ts
> +      const { resource, eventName } = body;
This should be moved to the webhook class because you are handling HTTP request data directly when it should be done in the API layer.

2023-12-19 21:45 UTC, xeno097 commented on src/modules/user/core/services/kyc.service.new.ts
> +    return { status: 200, message: exisitingResource ? 'RESOURCE_UPDATED' : 'RESOURCE_SAVED' };
This should be handled by the api layer as you are directly working with HTTP related data

2023-12-19 21:45 UTC, xeno097 commented on src/modules/user/infra/libs/metamap/metamap.kyc.provider.ts
> +    };
You could probably refactor this into a method that takes a URL endpoint and the params/request body so you can avoid repeating this logic in every method with the only changing bit being the params and the url

2023-12-19 21:45 UTC, xeno097 commented on src/modules/user/infra/libs/metamap/metamap.kyc.provider.ts
> +  private kycRequestRepository: IKycRequestRepository;
you are not initializing the repositories which will cause the app to crash when calling a method on any of those 2

2023-12-20 20:57 UTC, DHurtado714-itesm commented on src/modules/user/core/services/kyc.service.new.ts
Are yo sure? because the file `kyc.repository.ts` works on the db communication layer. This file works con the kyc main logic, which combines repository and provider layer.

2023-12-20 21:03 UTC, pellerano commented on src/modules/user/core/services/kyc.service.new.ts
Maybe not the entire file, but the class methods which only calls the repository feel redundant.

2023-12-21 23:54 UTC, xeno097 requested changes

2023-12-21 23:54 UTC, xeno097 commented on src/modules/user/enums/index.ts
> +}
I think a `COMPLETED` status is missing here

2023-12-21 23:54 UTC, xeno097 commented on src/modules/user/infra/libs/metamap/metamap.kyc.provider.ts
> +export class MetamapProvider {
Remember to create an abstract class to hide the implementation of the concrete provider itself like I did for the CognitoProvider which is the implementation for the AuthProvider class

2023-12-21 23:54 UTC, xeno097 commented on src/modules/user/infra/libs/metamap/metamap.kyc.provider.ts
> +    private kycRequestRepository: IKycRequestRepository
Please add the `readonly` modifier to each one of the injected classes. `private readonly ...`

2023-12-21 23:54 UTC, xeno097 commented on src/modules/user/infra/libs/metamap/metamap.kyc.provider.ts
> +  }
Is this supposed to stay like this?

2023-12-21 23:54 UTC, xeno097 commented on src/modules/user/api/webhook/metamap.webhook.ts
> +  constructor(private kycService: KycService) {}
Please add the `readonly` modifier

2023-12-21 23:54 UTC, xeno097 commented on src/modules/user/core/services/types.ts
> +}
Could you add documentation to the fields?

2023-12-21 23:54 UTC, xeno097 commented on src/modules/user/core/services/types.ts
> +  eventName: string;
Considering that the documentation specifies exactly which events type could be sent by the API can you create an enum that describes those types? Also, I see that this is used in the controller so it shouldn't be placed here or you should create a new type that is valid only in the core layer

2023-12-21 23:54 UTC, xeno097 commented on src/modules/user/infra/libs/metamap/metamap.kyc.provider.ts
> +  async getResouceData(resourceUrl: string): Promise<any> {
Please remember to add a return type that is not any

2023-12-21 23:54 UTC, xeno097 commented on src/modules/user/infra/libs/metamap/metamap.kyc.provider.ts
> +
This shouldn't be here as it uses the user repository

2023-12-21 23:54 UTC, xeno097 commented on src/modules/user/core/services/kyc.service.new.ts
> +});
This should be placed in the API layer as it is something graphql API specific

2023-12-21 23:54 UTC, xeno097 commented on src/modules/user/core/services/kyc.service.new.ts
> +  async updateUserVerified(uid: string, status: string) {
Remember to add return types

2023-12-21 23:54 UTC, xeno097 commented on src/modules/user/core/services/kyc.service.new.ts
> +    private constants: Constants
Please add the `readonly` modifier to these classes.

2023-12-21 23:54 UTC, xeno097 commented on src/modules/user/core/services/kyc.service.new.ts
> +      user.kycStatus = null;
Wouldn't it be better to have an unverified status for the user instead of setting it to null? Also I think we should throw an error if this method is called and the user is already verified

2023-12-21 23:54 UTC, xeno097 commented on src/modules/user/api/webhook/metamap.webhook.ts
> +  async completeVerification(@Req() request: MetamapBasePayload) {
I don't think that this will work because that payload is in the  `body` property of the request type. You should use the `Body` decorator to extract the payload from the request

2023-12-22 00:36 UTC, DHurtado714-itesm commented on src/modules/user/enums/index.ts
> +}
As it was on the previous implementation this was missing

2023-12-22 00:40 UTC, DHurtado714-itesm commented on src/modules/user/infra/libs/metamap/metamap.kyc.provider.ts
> +  }
I really don't know, it was like this. I can check if it's necessary

2023-12-29 01:35 UTC, xeno097 requested changes
I think that we are basically done with this only minor things remain and we can merge this

2023-12-29 01:35 UTC, xeno097 commented on src/modules/user/api/webhook/types.ts
> + */
I think that it would be better to move the description of each field above the corresponding field on the `MetamapBasePayload` interface so that when you hover over a field name the ide displays the field description and that way you don't need to repeat the name of the field because it is clear by just looking at the type definition

2023-12-29 01:35 UTC, xeno097 commented on src/modules/user/core/services/kyc.service.new.ts
> +      }
Remember to replace hard coded event names and statuses with the enums that you created

2024-01-03 22:43 UTC, xeno097 approved these changes

2024-01-30 00:00 UTC, xeno097 commented on src/modules/user/core/services/kyc.service.new.ts
> +    }
This if is not needed because if the update fails an error will be thrown anyways the update method does not return a boolean, it returns the updated entity

2024-01-30 00:00 UTC, xeno097 commented on src/modules/user/core/services/kyc.service.new.ts
> +    if (user.kycStatus !== 'VERIFIED') {
I see hardcoded strings here, also, if the user is already verified you should throw an error instead

2024-01-30 01:15 UTC, DHurtado714-itesm commented on src/modules/user/core/services/kyc.service.new.ts
> +      // await this.kycRepository.deleteByUserId(userIdEntity);
I was debating if we should implements, delete kyc Data when the operation is expired. What do you think?

2024-01-30 04:08 UTC, DHurtado714-itesm commented on src/modules/user/enums/index.ts
> +  REJECTED = 'FAILED',
Metamap has the status has `REJECTED`, but the DB has it as `FAILED`

2024-01-30 23:58 UTC, xeno097 requested changes

2024-01-30 23:58 UTC, xeno097 commented on src/modules/user/core/domain/value-objects/metamap.value-object.ts
> +export class MetamapResourceId extends BaseValueObject<string> {
Could you please rename this `KycExternalId`? This also means that you should update the error name

2024-01-30 23:58 UTC, xeno097 commented on src/modules/user/infra/repositories/kyc.repository.ts
> +  public async getByResourceId(id: string): Promise<KycEntity> {
Considering that we now have a dedicated type for the resource id could use it here?

2024-01-30 23:58 UTC, xeno097 commented on src/modules/user/core/errors/metamap.error.ts
> +  }
It would be better to leave the code as `VERIFIED_USER` or `USER_IS_VERIFIED` and update the error message to include the user's id. This way the front-end guys can handle the error without problems because the error code is predictable

2024-01-30 23:58 UTC, xeno097 commented on src/modules/user/infra/libs/metamap/metamap.kyc.provider.ts
> +    }
you don't need to perform this check anymore here as the config service will throw an error for you if this is not set

2024-01-30 23:58 UTC, xeno097 commented on src/modules/user/api/graphql/metamap.resolver.ts
> +  constructor(private readonly metamapService: KycService) {}
please rename the variable to `kycService`

2024-01-30 23:58 UTC, xeno097 commented on src/modules/user/core/services/kyc.service.new.ts
> +      // await this.kycRepository.deleteByUserId(userIdEntity);
if a KYC is expired a new one is created or the same can be restarted?

2024-01-31 01:37 UTC, xeno097 approved these changes

2024-01-31 01:40 UTC, xeno097 approved these changes

2024-02-05 21:49 UTC, merged