fix(cognito): is user auth in cognito flow
Alcancia-io/Alcancia-BackEnd pull request #136
Opened 2023-12-19 17:41 UTC by DHurtado714-itesm

Query in graphql for IsUserAuthenticated fucntion but in cognito flow.

2023-12-19 18:10 UTC, pellerano approved these changes

2023-12-19 21:07 UTC, xeno097 requested changes
I have question. Do we really need a `isUserAuthenticated` with the new flow considering that if the user is not, the backend will either inform the app that the token has expired or it is invalid if none is provided with a request?

2023-12-19 21:07 UTC, xeno097 commented on src/modules/user/infra/libs/cognito/cognito.auth.provider.ts
> +      console.error(error);
you can avoid logging the error here because the global catcher will take care of that

2023-12-19 21:07 UTC, xeno097 commented on src/modules/user/core/infra/auth-provider.ts
> +export interface isUserAuthenticatedDto {
The name should be `IsUserAuthenticated` ?

2023-12-19 21:07 UTC, xeno097 commented on src/modules/user/api/graphql/auth.resolver.new.ts
> +  async isUserAuthenticated(@JwtPayload(true) jwtPayload: JwtTokenPayloadV1): Promise<boolean> {
This should be renamed because it shadows the currently existing `isUserAuthenticated` query that supports the amplify auth flow

2023-12-20 15:56 UTC, AlbertoMorillo approved these changes

2023-12-21 01:19 UTC, xeno097 commented
I thnk that we all agree that this can be closed now

2023-12-21 01:19 UTC, closed without merging