Feat/Settings Module Refactor Part 1
Alcancia-io/Alcancia-BackEnd pull request #143
Opened 2024-01-10 19:21 UTC by pellerano

2024-01-18 01:53 UTC, xeno097 requested changes

2024-01-18 01:53 UTC, xeno097 commented on src/modules/settings/infra/repositories/apy.repository.ts
> +  }
If these methods are not going to be used you can remove them and simply not implement the BaseRepository interface

2024-01-18 01:53 UTC, xeno097 commented on src/modules/settings/infra/repositories/apy.repository.ts
> +      skip: 0,
skipping is not needed here if you are going to take the first element

2024-01-18 01:53 UTC, xeno097 commented on src/modules/settings/infra/repositories/apy.repository.ts
> +    };
Please assign fields one by one instead of spreading

2024-01-18 01:53 UTC, xeno097 commented on src/modules/settings/infra/repositories/apy.repository.ts
> +    const [apy] = await this.baseRepository.find({
Use `findOne` instead as we only need one value

2024-01-18 01:53 UTC, xeno097 commented on src/modules/settings/infra/repositories/apy.repository.ts
> +  public async getLastByToken(token: string): Promise<ApyEntity> {
Please rename this method to `getByToken` and use the `SupportedCryptoCurrency` enum instead of a simple string

2024-01-18 01:53 UTC, xeno097 commented on src/modules/settings/core/use-cases/get-current-apy.use-case.ts
> +}
Please implement the `IUsecase` interface and don't collapse everything in one line. You probably need to pull the changes from develop to have the `IUseCase` interface.

2024-01-18 01:53 UTC, xeno097 commented on src/modules/settings/api/graphql/settings.resolver.ts
> +  async getAPY(@Args('token') token: string) {
Please rename this to `getApyByToken` and use the `SupportedCryptoCurrency` enum

2024-01-18 01:53 UTC, xeno097 commented on src/modules/settings/core/domain/entities/apy.entity.ts
> +  token: string;
Please replace this with the `SupporteCryptoCurrency` enum

2024-01-24 22:52 UTC, xeno097 requested changes

2024-01-24 22:52 UTC, xeno097 commented on src/modules/settings/infra/repositories/apy.repository.ts
> +      token: SupportedCryptoCurrency[apy.token],
Please create a function that converts from a plain string to a valid enum variant of the `SupportedCryptoCurrency` enum. Example:
![image](https://github.com/Alcancia-io/Alcancia-BackEnd/assets/42520800/39476223-4d70-4b9d-8d0d-94c04747209f)

2024-01-24 22:52 UTC, xeno097 commented on src/modules/settings/api/graphql/settings.resolver.ts
> +  async getApyByToken(@Args('token') token: SupportedCryptoCurrency) {
Please add the return type to this method

2024-01-24 22:52 UTC, xeno097 commented on src/modules/settings/core/services/__tests__/apy.service.spec.ts
> +});
This test suite is testing a mock instead of the use case itself. Please test the use case as testing a mock is not needed

2024-01-24 22:52 UTC, xeno097 commented on src/modules/settings/core/use-cases/get-current-apy.use-case.ts
> +  public async execute({ token }: ExecuteGetCurrentApyUseCaseDto) {
Please add an empty line between the constructor and the method implementation. The same applies for the line below this one. Add an empty line between the return statement and the repository call

2024-01-24 22:52 UTC, xeno097 commented on src/modules/settings/core/use-cases/get-current-apy.use-case.ts
> +  constructor(private apyRepository: IApyRepository) {}
Please add the `readonly` modifier

2024-01-26 21:24 UTC, DHurtado714-itesm submitted a review, later dismissed

2024-01-27 01:22 UTC, xeno097 requested changes

2024-01-27 01:22 UTC, xeno097 commented on src/modules/settings/infra/repositories/apy.repository.ts
> +}
Please move this to the `src/modules/settings/core/infra` folder like for the providers and repositories in the user module.
![image](https://github.com/Alcancia-io/Alcancia-BackEnd/assets/42520800/37c7163b-8df6-4d3f-8144-30dc88de7ddc)

2024-01-27 01:22 UTC, xeno097 commented on src/modules/settings/api/graphql/object-types/types.ts
> +  rate: string;
Please follow the convention of appending the API scope to the type. Example:
![image](https://github.com/Alcancia-io/Alcancia-BackEnd/assets/42520800/50cf9696-8b5c-4292-b48d-beb7f65fa641)

2024-01-29 22:57 UTC, xeno097 requested changes

2024-01-29 22:57 UTC, xeno097 commented on src/modules/settings/api/graphql/object-types/types.ts
>  export class AppVersion {
This should be `AppVersionGraphQLObject`

2024-01-29 22:57 UTC, xeno097 commented on src/modules/settings/api/graphql/object-types/types.ts
> +export class GetApyByTokenResponse {
This should be `GetApyByTokenGraphQLResponse`

![image](https://github.com/Alcancia-io/Alcancia-BackEnd/assets/42520800/cb5de6a4-8d0c-43db-a149-c1396c242a02)

2024-01-30 00:06 UTC, xeno097 requested changes

2024-01-30 00:06 UTC, xeno097 commented on src/modules/settings/api/graphql/object-types/types.ts
> +@ObjectType('AppVersionGraphQLObject')
Could you please follow the example faithfully? The string does not have `GraphQL` in it anywhere
![image](https://github.com/Alcancia-io/Alcancia-BackEnd/assets/42520800/5ebf525e-2ea9-4683-b48b-9972e7c47403)

2024-01-30 00:06 UTC, xeno097 commented on src/modules/settings/api/graphql/object-types/types.ts
> +export class GetApyByTokenGraphQLResponse {
Same here

2024-01-31 00:00 UTC, xeno097 requested changes

2024-01-31 00:00 UTC, xeno097 commented on src/modules/settings/api/graphql/object-types/types.ts
> +@ObjectType('AppVersionObject')
Here you can simply leave it as `AppVersion`

2024-01-31 20:51 UTC, xeno097 approved these changes

2024-02-05 21:55 UTC, merged