Notification module refactor part 2
Alcancia-io/Alcancia-BackEnd pull request #153
Opened 2024-01-18 15:42 UTC by DHurtado714-itesm

Implemented the base use-cases for notifications module

2024-01-18 15:50 UTC, xeno097 requested changes
Please add unit tests to the use case

2024-01-18 15:50 UTC, xeno097 commented on src/modules/notifications/core/use-cases/deposit-notfication.use-case.ts
> +  constructor(private firebaseNotificationProvider: FirebaseNotificationsProvider) {}
please add the `readonly` modifier after `private` and use the interface instead of the concrete implementation `FirebaseNotificationsProvider` if don't have one create a `INotificationProvider` interface as we did for the repositories.

2024-01-18 15:50 UTC, xeno097 commented on src/modules/notifications/core/use-cases/deposit-notfication.use-case.ts
> +        throw new Error('Invalid deposit status');
Please create a custom error using the provided classes

2024-01-18 21:41 UTC, xeno097 requested changes

2024-01-18 21:41 UTC, xeno097 commented on src/modules/notifications/infra/lib/firebase/firebase.notifications.provider.ts
>    private firebaseConfig: FirebaseConfig;
It should be `extends` instead of implements as it is inheriting from an abstract class

2024-01-18 21:41 UTC, xeno097 commented on src/modules/notifications/core/use-cases/test/deposit-use-case.test.ts
> +  });
Please use the same test structure used in the other unit tests . See [this](https://dev.to/coderjay06/the-three-a-s-of-unit-testing-b22) article for what I'm talking about

2024-01-18 21:41 UTC, xeno097 commented on src/modules/notifications/core/use-cases/test/deposit-use-case.test.ts
> +  it('should throw InvalidOrderStatusError for an invalid status', async () => {
you can use the class to get the name instead of manually typing it so that if for whatever reason we change the name of the error it is automatically changed here. Example:
![image](https://github.com/Alcancia-io/Alcancia-BackEnd/assets/42520800/d6b21d34-2432-4142-8dd2-4859db69b7fd)

2024-01-18 21:41 UTC, xeno097 commented on src/modules/notifications/core/use-cases/test/deposit-use-case.test.ts
> +describe('DepositUseCase', () => {
Same comment as below you can directly use the class and take its name

2024-01-18 21:41 UTC, xeno097 commented on src/modules/notifications/core/use-cases/test/deposit-use-case.test.ts
> +    };
Please create a mock function in a separate file as done in the other tests. Example:
![image](https://github.com/Alcancia-io/Alcancia-BackEnd/assets/42520800/dc70f1a4-85c6-4a50-ba31-4830e1ee9462)

2024-01-18 21:41 UTC, xeno097 commented on src/modules/notifications/core/errors/invalid-status.error.ts
> +}
I think that this should `extend` from `BaseInternalError` because is not an error caused by a user input but instead it is caused by a programming bug. It would also be a good idea to add which ones are the valid values from the enum.

2024-01-18 21:41 UTC, xeno097 commented on src/modules/notifications/core/use-cases/deposit-notfication.use-case.ts
> +export class DepositUseCase implements IUseCase<DepositNotificationUseCaseDTO, Promise<void>> {
you can simply put `void` as the return type without the `Promise`

2024-01-18 21:41 UTC, xeno097 commented on src/modules/notifications/core/use-cases/test/deposit-use-case.test.ts
> +}
Do we really need an enum for this?

2024-01-19 16:41 UTC, DHurtado714-itesm commented on src/modules/notifications/core/use-cases/test/deposit-use-case.test.ts
> +}
I need to add more Order types, but yes, for not using any hardcoded strings

2024-01-19 22:45 UTC, pellerano submitted a review, later dismissed

2024-01-25 21:23 UTC, xeno097 requested changes
One final note is that my preference would be for use cases Dtos to be placed in the same file as their use case. Example:

![image](https://github.com/Alcancia-io/Alcancia-BackEnd/assets/42520800/4251c987-49c8-4a2a-b7c6-4af89e96f42f)

2024-01-25 21:23 UTC, xeno097 commented on src/modules/notifications/infra/lib/firebase/firebase.notifications.provider.ts
>    async sendPushNotification(notification: NotificationMessage, deviceToken: string): Promise<void> {
Considering that you created a `DeviceToken` type, use that instead of a plain string so you don't need to verify that the string is defined.

2024-01-25 21:23 UTC, xeno097 commented on src/modules/notifications/infra/lib/firebase/firebase.notifications.provider.ts
>      }
You can remove this error checking as neither of the function parameters can be undefined

2024-01-25 21:23 UTC, xeno097 commented on src/modules/notifications/core/dto/validator/device-token.validator.ts
> +}
This file should be placed under the folder `src/modules/notifications/core/domain/value-objects` as you can see from the structure of the `user` module

2024-01-25 21:23 UTC, xeno097 commented on src/modules/notifications/core/services/notification.service.ts
> +}
This file can be removed entirely as use cases should not be used in service classes but instead should be invoked directly by their callers being it a controller or any other public API.

2024-01-25 21:23 UTC, xeno097 commented on src/modules/notifications/core/enums/notification.enums.ts
> +}
considering that this enum is new I'd prefer to use a string instead of a number for the internal value as you did it for the `OrderTypeEnum`

2024-01-25 21:23 UTC, xeno097 commented on src/modules/notifications/core/enums/notification.enums.ts
> +}
We should reach an agreement on enum naming because sometimes you add the `Enum` suffix and sometimes you don't which makes code inconsistent. Considering that the majority of the code does not use the `Enum` suffix, I'd remove it here.

2024-01-25 21:23 UTC, xeno097 commented on src/modules/notifications/core/infra/__test__/mocks/notifications.provider.mock.ts
> +export const sendPushNotificationMock = (): jest.Mocked<INotificationsProvider> => {
Please rename the function to `getNotificationProviderMock` to follow the convention for naming functions that create mocked classes.

2024-01-25 21:23 UTC, xeno097 commented on src/modules/notifications/core/use-cases/test/deposit-use-case.test.ts
> +const DEVICE_TOKEN = '';
Should this be empty?

2024-01-25 21:23 UTC, xeno097 commented on src/modules/notifications/core/use-cases/test/metamap-use-case.test.ts
> +const DEVICE_TOKEN = '';
x2

2024-01-25 21:23 UTC, xeno097 commented on src/modules/notifications/core/use-cases/test/withdraw-use-case.test.ts
> +const DEVICE_TOKEN = '';
x3

2024-01-25 21:23 UTC, xeno097 commented on src/modules/notifications/core/dto/notification-use-case.dto.ts
> +export interface DepositNotificationUseCaseDTO {
Please rename this to `DepositNotificationUseCaseDto` the same applies to all the other types that have the `DTO` suffix.

2024-01-26 16:06 UTC, DHurtado714-itesm commented on src/modules/notifications/core/use-cases/test/deposit-use-case.test.ts
> +const DEVICE_TOKEN = '';
It depends on the dev who is testing, each one should use their own DEVICE_TOKEN

2024-01-26 16:07 UTC, DHurtado714-itesm commented on src/modules/notifications/core/enums/notification.enums.ts
> +}
Here `src/utils/enums/index.ts` we have a enum which specifies the Transaction type for the database, I am using the same logic

2024-01-27 01:27 UTC, xeno097 requested changes

2024-01-27 01:27 UTC, xeno097 commented on src/modules/notifications/core/use-cases/test/deposit-use-case.test.ts
> +// TODD: check this with @Sebastiano
I think that you can remove these comments now

2024-01-27 01:27 UTC, xeno097 commented on src/modules/notifications/core/enums/notification.enums.ts
> +}
I think you forgot to update this here

2024-01-31 00:02 UTC, xeno097 submitted a review, later dismissed

2024-02-05 22:01 UTC, merged